
#
# Root Directory for project
#
TOP= ./../../../projects

#
# Include the general platform independent Makefile
#
include $(TOP)/Makefile.include.gen

#*****************************************************************************#
#                               Object FILE LIST                              #
#*****************************************************************************#
#OBJS = 	$(BUILD_ROOT_OBJ)/lmp.o \
#		$(BUILD_ROOT_OBJ)/lmp_1_2_pdu.o \
#		$(BUILD_ROOT_OBJ)/lmp_afh.o \
#		$(BUILD_ROOT_OBJ)/lmp_datamgr.o \
#		$(BUILD_ROOT_OBJ)/lmp_pdu.o \
#		$(BUILD_ROOT_OBJ)/lmp_sync_links.o \
#		$(BUILD_ROOT_OBJ)/lmp_sco.o \
#		$(BUILD_ROOT_OBJ)/lmp_tasks.o \
#		$(BUILD_ROOT_OBJ)/lmp_ch_assessment.o \
#		$(BUILD_ROOT_OBJ)/lmp_pdu_q.o \
#		$(BUILD_ROOT_OBJ)/lmp_2_1.o \
#		$(BUILD_ROOT_OBJ)/lmp_edtm.o \
#		$(BUILD_ROOT_OBJ)/lmp_utils.o
		
OBJS = 	
OBJS += lmp.o
OBJS += lmp_1_2_pdu.o
OBJS += lmp_afh.o
OBJS += lmp_datamgr.o
OBJS += lmp_pdu.o
OBJS += lmp_sync_links.o
OBJS += lmp_sco.o
OBJS += lmp_tasks.o
OBJS += lmp_ch_assessment.o
OBJS += lmp_pdu_q.o
OBJS += lmp_2_1.o
OBJS += lmp_edtm.o
OBJS += lmp_utils.o
OBJS += lmp_3_0.o
OBJS += lmp_4_1.o
		
#*****************************************************************************#
#                        RULES TO GENERATE TARGETS                            #
#*****************************************************************************#
all: CORE_TARGETS COPY_OBJS

#*****************************************************************************#
#              GENERATE OBJECT FILE 
#*****************************************************************************#
CORE_TARGETS:	$(OBJS) 

#*****************************************************************************#
#                             END OF MAKEFILE                                 #
#*****************************************************************************#

