/***************************************************************************
 Copyright (C) Mindtree Ltd.
 This module is a confidential and proprietary property of MindTree and
 a possession or use of this module requires written permission of MindTree.
 ***************************************************************************/

#ifndef __BT_FW_ERRORS_H__
#define __BT_FW_ERRORS_H__

/* General type of errors. */

#define BT_FW_NULL                        0

#define BT_FW_SUCCESS                     1

#define BT_FW_ERROR                    0xFF

/*Invalid Arguments  */
#define BT_FW_IARG                        2

/* Not enough memory */
#define BT_FW_NOMEM                       3

/*Resource not Exists*/
#define BT_FW_NOT_EXIST                   4

/*Operation timedout */
#define BT_FW_TIMEOUT                     5


/* Errors generated by the OS module */

#define    ERROR_NULL_POINTER                    1

#define    ERROR_OS_INVALID_TASK_PRIO          101

#define    ERROR_OS_DUPLICATE_TASK_PRIO        102

#define    ERROR_OS_INVALID_QUEUE_SIZE         103

#define    ERROR_OS_INVALID_BUSY_PERIOD        104

#define    ERROR_OS_INVALID_TASK_FUNC          105

#define    ERROR_OS_INVALID_TASK               106

#define    ERROR_OS_INVALID_EXT_EVENT          107

#define    ERROR_OS_INVALID_TIMER_FUNC         108

#define    ERROR_OS_INVALID_TIMER_TYPE         109

#define    ERROR_OS_TIMER_POOL_EXHAUSTED       110

#define    ERROR_OS_INVALID_TIMER              111

#endif /* __BT_SIGNALS_H__ */
